### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by hatjs880328s** [425358558/EWS-for-iOS#11]
我们用的exchange 2010 sp3 貌似不行。。

**Comment by ankushkushwaha** [comment]
Can you provide details about this issue?

**Comment by hatjs880328s** [comment]
it can works . my configuration is incorrect .

Now have a problem , can u help me ？ 



<?xml version="1.0" encoding="utf-8"?>
     <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
     xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
     xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
     <soap:Body>
     <m:CreateItem MessageDisposition="SendAndSaveCopy">
     <m:SavedItemFolderId>
     <t:DistinguishedFolderId Id="sentitems" />
     </m:SavedItemFolderId>
     <m:Items>
     <t:Message>
     <t:Subject>Company Soccer Team</t:Subject>
     <t:Body BodyType="HTML">From ios exchange...</t:Body>
     <t:ToRecipients>
     <t:Mailbox>
     <t:EmailAddress>451145552@qq.com </t:EmailAddress>
     </t:Mailbox>
     </t:ToRecipients>
     </t:Message>
     </m:Items>
     </m:CreateItem>
     </soap:Body>
     </soap:Envelope>


HI,this is SEND - EMAIL xml 
Cant works .
alert : 
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="415" MinorBuildNumber="0" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:CreateItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:CreateItemResponseMessage ResponseClass="Error"><m:MessageText>一个或多个收件人无效。</m:MessageText><m:ResponseCode>ErrorInvalidRecipients</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:Items/></m:CreateItemResponseMessage></m:ResponseMessages></m:CreateItemResponse></s:Body></s:Envelope>

**Comment by hatjs880328s** [comment]
it can works.


<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <soap:Body>
    <CreateItem MessageDisposition="SendAndSaveCopy" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
      <SavedItemFolderId>
        <t:DistinguishedFolderId Id="drafts" />
      </SavedItemFolderId>
      <Items>
        <t:Message>
          <t:ItemClass>IPM.Note</t:ItemClass>
          <t:Subject>Project Action</t:Subject>
          <t:Body BodyType="Text">Priority - Update specification</t:Body>
          <t:ToRecipients>
            <t:Mailbox>
              <t:EmailAddress>451145552@qq.com</t:EmailAddress>
            </t:Mailbox>
          </t:ToRecipients>
          <t:IsRead>false</t:IsRead>
        </t:Message>
      </Items>
    </CreateItem>
  </soap:Body>
</soap:Envelope>


it's send email XML
