### ISSUE TITLE
It's doesn't work

### ISSUE THREAD

**Issue by coooliang** [425358558/EWS-for-iOS#3]
I use url https://mail.xxxxxx.com/EWS/Exchange.asmx is fail
but use java-ews-api framework can connection url and get inbox list

**Comment by ankushkushwaha** [comment]
@coooliang are you using office 365 account?

**Comment by coooliang** [comment]
@ankushkushwaha  no no no, I used my company email account,  exchange Server

**Comment by ankushkushwaha** [comment]
So you have your own ewsurl for that server, means no need to autodiscover the authenticated url?
