### ISSUE TITLE
Show email content in the UI instead of showing in Xcode log terminal for better user experience?

### ISSUE THREAD

**Issue by ankushkushwaha** [425358558/EWS-for-iOS#9]
Hi,

For the first-timer, it is hard to understand, what is going on after entering the credentials, as there is nothing happing in UI. I tried to add activity-indicator but still, it seems like the app is doing nothing until the user sees the Xcode logs. We can try to show inbox's first email content or list of emails into a table view into next screen after the successful authentication with the exchange. 

Let me know what do you think

**Comment by 425358558** [comment]
Hi,

In the beginning, this project is just a functional module for a app. So, you can see the UI is really simple. But now, I'm no longer using Exchange e-mail, and I have no EWS server for developing this module.I haven't updated the code for a long time. Improving UI for better user experience is a good idea. You can add UI code to this project as you want. If there is anything I can help, please let me know.
